### ISSUE TITLE
fix wrong import utils：'path_to_image' from 'utils'

### ISSUE THREAD

**Issue by juntaosun** [ZHO-ZHO-ZHO/ComfyUI-BiRefNet-ZHO#25]
Why hasn't this bug fix been merged in 6 months? Is this project still maintained?

```
Cannot import F:\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-BiRefNet-ZHO module for custom nodes: cannot import name 'path_to_image' from 'utils' (F:\ComfyUI-aki-v1.1\utils\__init__.py) 
```

fixes it：
https://github.com/ZHO-ZHO-ZHO/ComfyUI-BiRefNet-ZHO/issues/23#issuecomment-2357419059

Is this project still maintained?

**Comment by louis-she** [comment]
#26
